extends:
  - airbnb
  - prettier
  - prettier/react

plugins:
  - react
  - jsx-a11y
  - import
  - prettier

env:
  browser: true
  jest: true

rules:
  class-methods-use-this: off
  no-else-return: off
  prefer-destructuring: off
  import/prefer-default-export: off
  react/no-array-index-key: off
  react/prefer-stateless-function: off
  react/forbid-prop-types: off
  react/jsx-filename-extension: off
  jsx-a11y/no-static-element-interactions: off
  valid-jsdoc: error

  # Only for accounts
  no-alert: off

  prettier/prettier:
    - warn
    -
      printWidth: 100
      tabWidth: 4
      singleQuote: true
