version: '3'

services:

  frontend:
    build:
      context: frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend/:/app/
      - /app/node_modules
    depends_on:
      - backend
    command: sh -c 'yarn && yarn start'

  backend:
    build:
      context: backend
    environment:
      - CORS_ORIGIN=http://0.0.0.0:3001
    volumes:
      - ./backend/:/app/
      - /app/node_modules
    ports:
      - "3000:3000"