version: '3'

services:

  frontend:
    build:
      context: frontend
    ports:
      - "3001:3001"
    volumes:
      - "./frontend/:/app"
    depends_on:
      - backend
      
  backend:
    build:
      context: backend
    volumes:
      - "./backend/:/app"
    ports:
      - "3000:3000"