version: '3'
services:

  frontend:
    build:
      context: frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/package.json:/app/package.json
    depends_on:
      - backend

  backend:
    build:
      context: backend
    environment:
      - CORS_ORIGIN=http://localhost:3001
      - WEB_APP_URL=http://localhost:3001
    volumes:
      - ./backend/:/app/
      - /app/node_modules
    ports:
      - "3000:3000"