version: '3'
services:

  frontend:
    build:
      context: frontend
    ports:
      - "3002:3002"
    depends_on:
      - backend
    command: "yarn start"

  backend:
    build:
      context: backend
    environment:
      - CORS_ORIGIN=http://localhost:3002
      - WEB_APP_URL=http://localhost:3002
    volumes:
      - ./backend/:/app/
      - /app/node_modules
    ports:
      - "3000:3000"